[2024-07-20 11:45:28,186: INFO: stage_prepare_base_model_02: *******************]
[2024-07-20 11:45:28,187: INFO: stage_prepare_base_model_02: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2024-07-20 11:45:28,187: ERROR: stage_prepare_base_model_02: ConfigurationManager.get_prepare_base_model_config() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "/home/liszt87/python_project/End2End-Deep-Learning-Project/src/cnnClassifier/pipeline/stage_prepare_base_model_02.py", line 25, in <module>
    obj.main()
  File "/home/liszt87/python_project/End2End-Deep-Learning-Project/src/cnnClassifier/pipeline/stage_prepare_base_model_02.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
TypeError: ConfigurationManager.get_prepare_base_model_config() missing 1 required positional argument: 'self'
[2024-07-20 11:48:00,389: INFO: stage_prepare_base_model_02: *******************]
[2024-07-20 11:48:00,390: INFO: stage_prepare_base_model_02: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2024-07-20 11:48:00,390: ERROR: stage_prepare_base_model_02: [Errno 2] No such file or directory: 'config/config.yaml']
Traceback (most recent call last):
  File "/home/liszt87/python_project/End2End-Deep-Learning-Project/src/cnnClassifier/pipeline/stage_prepare_base_model_02.py", line 25, in <module>
    obj.main()
  File "/home/liszt87/python_project/End2End-Deep-Learning-Project/src/cnnClassifier/pipeline/stage_prepare_base_model_02.py", line 12, in main
    config = ConfigurationManager()
  File "/home/liszt87/python_project/End2End-Deep-Learning-Project/src/cnnClassifier/config/configuration.py", line 12, in __init__
    self.config = read_yaml(config_filepath)
  File "/home/liszt87/python_project/End2End-Deep-Learning-Project/.venv/lib/python3.10/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/home/liszt87/python_project/End2End-Deep-Learning-Project/src/cnnClassifier/utils/common.py", line 36, in read_yaml
    raise e
  File "/home/liszt87/python_project/End2End-Deep-Learning-Project/src/cnnClassifier/utils/common.py", line 29, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
